# Generated by Django 4.2.2 on 2023-07-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razorpaybackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(verbose_name='Amount'),
        ),
    ]
